[title_akas]
"titleId (string)" = "a tconst, an alphanumeric unique identifier of the title"
"ordering (integer)" = "a number to uniquely identify rows for a given titleId"
"title (string)" = "the localized title"
"region (string)" = "the region for this version of the title"
"language (string)" = "the language of the title"
"types (array)" = "Enumerated set of attributes for this alternative title. One or more of the following: alternative, dvd, festival, tv, video, working, original, imdbDisplay. New values may be added in the future without warning"
"attributes (array)" = "Additional terms to describe this alternative title, not enumerated"
"isOriginalTitle (boolean)" = "0: not original title; 1: original title"

[title_basics]
"tconst (string)" = "alphanumeric unique identifier of the title"
"titleType (string)" = "the type/format of the title (e.g. movie, short, tvseries, tvepisode, video, etc)"
"primaryTitle (string)" = "the more popular title / the title used by the filmmakers on promotional materials at the point of release"
"originalTitle (string)" = "original title, in the original language"
"isAdult (boolean)" = "0: non-adult title; 1: adult title"
"startYear (int)" = "represents the release year of a title. In the case of TV Series, it is the series start year"
"endYear (int)" = "TV Series end year. NULL for all other title types"
"runtimeMinutes (int)" = "primary runtime of the title, in minutes"
"genres (string array)" = "includes up to three genres associated with the title"

[title_crew]
"tconst (string)" = "alphanumeric unique identifier of the title"
"directors (array of nconsts)" = "director(s) of the given title"
"writers (array of nconsts)" = "writer(s) of the given title"

[title_episode]
"tconst (string)" = "alphanumeric identifier of episode"
"parentTconst (string)" = "alphanumeric identifier of the parent TV Series"
"seasonNumber (integer)" = "season number the episode belongs to"
"episodeNumber (integer)" = "episode number of the tconst in the TV series"

[title_principals]
"tconst (string)" = "alphanumeric unique identifier of the title"
"ordering (integer)" = "a number to uniquely identify rows for a given titleId"
"nconst (string)" = "alphanumeric unique identifier of the name/person"
"category (string)" = "the category of job that person was in"
"job (string)" = "the specific job title if applicable, else NULL"
"characters (string)" = "the name of the character played if applicable, else NULL"

[title_ratings]
"tconst (string)" = "alphanumeric unique identifier of the title"
"averageRating (float)" = "weighted average of all the individual user ratings"
"numVotes (int)" = "number of votes the title has received"

[name_basics]
"nconst (string)" = "alphanumeric unique identifier of the name/person"
"primaryName (string)" = "name by which the person is most often credited"
"birthYear (int)" = "in YYYY format"
"deathYear (int)" = "in YYYY format if applicable, else NULL"
"primaryProfession (array of strings)" = "the top-3 professions of the person"
"knownForTitles (array of tconsts)" = "titles the person is known for"